---
title: "Rochester's Trees"
format: 
  dashboard:
    theme: [cosmo]
execute:
  echo: false
---

## Trees Map

```{r setup, inclue=FALSE}
library(tidyverse)
library(plotly)
library(rjson)
library(tidylog)
library(sf)

roc_trees_geo <- read_sf('data/roc_trees.geojson')
roc_zones <- read_sf('data/roc_zones.geojson')


  
```

```{r graphs, include=FALSE}


trees_plot <- plot_ly() |>
    add_sf(
    data = roc_trees_geo,
    color = 'red',
        type = "scattermapbox") |>
   layout(
    mapbox = list(
      style = "open-street-map",
      zoom = 11,
      # Center coordinates for Rochester, NY
      center = list(lon = -77.6158, lat = 43.1566)  
    ))



```

```{r zone, include=FALSE}


plot_ly() |>
    add_sf(data = roc_zones, 
           color = I("blue"), 
           fill = I("lightblue"), 
           opacity = 0.8,
           type = "scattermapbox") |>
  layout(
    mapbox = list(
      zoom = 10,  # Initial zoom level
      center = list(lon = -77.6158, lat = 43.1566)  # Center coordinates for Rochester, NY
    )
  )
```

# Trees in Rochester

```{r}
#| title: Over Time

trees_plot
#

```
